### ISSUE TITLE
cant download origin image

### ISSUE THREAD

**Issue by lich13** [krishh-konar/Twitter_Image_Downloader#1]
downloaded:
![image](https://cloud.githubusercontent.com/assets/10644698/19019263/3af8edbe-88b4-11e6-80c8-41121701e398.png)

origin:
![image](https://cloud.githubusercontent.com/assets/10644698/19019266/4d0e6aec-88b4-11e6-898c-ec18e1b8bdd1.png)

**Comment by krishh-konar** [comment]
Can you please elaborate a bit more?
